# Generated by Django 4.2.6 on 2024-02-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing_comment_bid_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='ends_at',
        ),
    ]
